### ISSUE TITLE
Supporting ST_within

### ISSUE THREAD

**Issue by Zizico2** [vitaly-m/postgis-diesel#12]
Is there any reason `ST_within` was left out but `ST_contains` is implemented?
I could try to implement this if you would accept a contribution for that.

**Comment by Zizico2** [comment]
Ok, I looked into the code and realized the question isn't that well phrased. But still the core is would there be interest in supporting within

**Comment by Zizico2** [comment]
Aaaaaand close this I shall. I guess within its just contained_by

**Comment by vitaly-m** [comment]
Hi @Zizico2, function has been supported in v2.1.0 as well as others from [Topological Relationships](https://postgis.net/docs/reference.html#idm12212) section.
