### ISSUE TITLE
Use GeoJSON standard

### ISSUE THREAD

**Issue by Plunts** [vitaly-m/postgis-diesel#16]
First of all: thanks for the lib 😄 

I wonder if it would be possible to use the [GeoJSON](https://geojson.org/) standard instead of the current structure that resembles the internal structure. Since I'm not too deep into rust at this point, I don't know if it could be configurable without overhead to avoid making it a breaking change though. But it would greatly increase compatibility for other software, for example [Leaflet](https://leafletjs.com/reference.html).

**Comment by vitaly-m** [comment]
Thank you for contribution, published in [v2.2.0](https://github.com/vitaly-m/postgis-diesel/releases/tag/v2.2.0)
